# Supabase CLI configuration file
# https://supabase.com/docs/guides/cli/config

project_id = "spotfinder"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = false
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = false
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
inspector_port = 8083

