name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Deploy Edge Functions
      run: |
        supabase functions deploy telegram-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Setup Telegram Webhook
      run: |
        deno run --allow-env --allow-net scripts/setup-webhook.ts
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        ENVIRONMENT: production

    - name: Verify Deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🔗 Webhook URL: https://${{ secrets.SUPABASE_PROJECT_ID }}.functions.supabase.co/telegram-webhook"
        echo "📊 Check webhook status: https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getWebhookInfo"

