name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.40.0
        
    - name: Cache Deno dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
        restore-keys: |
          ${{ runner.os }}-deno-
          
    - name: Run tests with coverage
      run: |
        cd supabase/functions
        deno test --allow-all --coverage=coverage/ --parallel
        
    - name: Generate coverage report
      run: |
        cd supabase/functions
        deno coverage coverage/ --lcov --output=coverage/lcov.info
        
    - name: Generate HTML coverage report
      run: |
        cd supabase/functions
        deno coverage coverage/ --html --output=coverage/html
        
    - name: Display coverage summary
      run: |
        cd supabase/functions
        deno coverage coverage/ --summary
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: supabase/functions/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: supabase/functions/coverage/
        retention-days: 30
        
    - name: Check coverage threshold
      run: |
        cd supabase/functions
        COVERAGE_PERCENT=$(deno coverage coverage/ --summary | grep -o '[0-9]\+\.[0-9]\+%' | head -1 | sed 's/%//')
        echo "Coverage: ${COVERAGE_PERCENT}%"
        
        # Check if coverage is above 70%
        if (( $(echo "$COVERAGE_PERCENT >= 70" | bc -l) )); then
          echo "✅ Coverage threshold (70%) met!"
        else
          echo "❌ Coverage below threshold (70%). Current: ${COVERAGE_PERCENT}%"
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.40.0
        
    - name: Run linter
      run: |
        cd supabase/functions
        deno lint --allow-all
        
    - name: Check formatting
      run: |
        cd supabase/functions
        deno fmt --check

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.40.0
        
    - name: Run security audit
      run: |
        cd supabase/functions
        deno audit --allow-all
