name: Test and Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run Tests
      run: |
        deno test --allow-all supabase/functions/_shared/*_test.ts

    - name: Check Formatting
      run: |
        deno fmt --check supabase/functions/

    - name: Run Linter
      run: |
        deno lint supabase/functions/

    - name: Type Check
      run: |
        deno check supabase/functions/_shared/*.ts